config/routes.rb
Suitor::Application.routes.draw do
  devise_for :user, skip: [
    :sessions
  ], controllers: {
    confirmations: 'user/confirmations',
    invitations: 'user/invitations',
    omniauth_callbacks: 'user/omniauth_callbacks',
    registrations: 'user/registrations',
    passwords: 'user/passwords'
  }
  devise_scope :user do
    get 'use-invite' => 'user/invitations#edit', as: :invitation_accept
    get 'invite' => 'user/invitations#new', as: :new_invitation

    get 'login' => 'devise/sessions#new', as: :login
    post 'login' => 'devise/sessions#create', as: :session
    delete 'logout' => 'devise/sessions#destroy', as: :logout

    get 'sign-up' => 'user/registrations#new', as: :signup
    post 'sign-up' => 'user/registrations#create', as: :create_user_registration
  end

  resource :user, as: :profile, path: 'profile',
                  except: [:new, :show, :index, :create, :destroy]

  resources :blog, only: [:index, :show]

  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'

  # If user is logged in, show the dashboard as root
  authenticated do
    root :to => 'dashboard#index', as: :dashboard
  end

  # If user isn't logged in, show the launch page as root
  root :to => 'pages#launch'

  # Set up job postings, and routing for nested models
  resources :postings do
    get 'archived', on: :collection
    member do
      put :archivetoggle
    end
    resource :job_application do
      member do
        put 'followup'
      end
    end
    resources :interviews
    resource :offer
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
  devise :database_authenticatable, :confirmable, :invitable, :lockable,
         :registerable, :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  # validates_presence_of :email
  # validates_format_of :email, with: EMAIL_REGEX, allow_blank: false

  has_many :postings, dependent: :destroy
  has_many :job_applications, through: :postings

  validates :email, uniqueness: true

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.photo = auth.info.image

      # Automatically confirm this user's email since they're using it with
      # Facebook.
      user.confirm! unless user.confirmed?
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] and session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def set_default_role
    self.role ||= :user
  end

  def activity_start_date
    unless job_applications.blank?
      job_applications.order('date_sent ASC').limit(1).first.date_sent
    end
  end

  def total_applications
    job_applications.count
  end

  def applications_per_week
    if !job_applications.nil?
      ((Time.now - activity_start_date.to_datetime).to_i / (60 * 60 * 24 * 7)).to_f / total_applications.to_f
    end
  end

  def update_tracked_fields!(request)
    super(request) unless admin?
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController

  private

    def after_confirmation_path_for(resource_name, resource)
      flash[:notice] = 'Thanks for confirming your email. You’re all set!'
      if current_user.nil?
        login_path
      else
        dashboard_path
      end
    end
end

app/controllers/user/invitations_controller.rb
class User::InvitationsController < Devise::InvitationsController
  before_filter :configure_permitted_parameters
  before_filter :require_admin, only: [:new, :remove, :destroy]

  protected

    def configure_permitted_parameters
      # Add user settings as allowed params for invites.
      [:accept_invitation, :invite].each do |c|
        devise_parameter_sanitizer.for(c).concat [:name]
      end
    end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    # (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # this will throw if
                                                            # @user is not
                                                            # activated
      if is_navigational_format?
        set_flash_message(:notice, :success, :kind => "Facebook")
      end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController

  private

    # The path used after sending reset password instructions
    def after_sending_reset_password_instructions_path_for(resource_name)
      login_path if is_navigational_format?
    end

    # Check if a reset_password_token is provided in the request
    def assert_reset_token_passed
      if params[:reset_password_token].blank?
        set_flash_message(:alert, :no_token)
        redirect_to login_path
      end
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
  before_filter :redirect_if_in_production

  protected

    def after_inactive_sign_up_path_for(resource)
      home_path
    end

    def after_sign_up_path_for(resource)
      home_path
    end

    def configure_permitted_parameters
      # Add user settings as allowed params for editing
      [:sign_up, :account_update].each do |c|
        devise_parameter_sanitizer.for(c).concat [:name, :followup_offset, :application_goal]
      end
    end

    def redirect_if_in_production
      redirect_to root_path if Rails.env.production?
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  private

    def after_confirmation_path_for(resource_name, resource)
      flash[:notice] = 'Thanks for confirming your email. You’re all set!'
      new_user_session_path
    end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_filter :configure_permitted_parameters
  before_filter :require_admin, only: [:new, :remove, :destroy]

  protected

    def configure_permitted_parameters
      # Add user settings as allowed params for invites.
      [:accept_invitation, :invite].each do |c|
        devise_parameter_sanitizer.for(c).concat [:name]
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    # (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # this will throw if
                                                            # @user is not
                                                            # activated
      if is_navigational_format?
        set_flash_message(:notice, :success, :kind => "Facebook")
      end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        # If we're changing the user's password, Devise will invalidate all
        # sessions as this user, so let's check to see if that's happened and
        # reauthenticate them if so.
        if user_params.key?(:password) and current_user.id == @user.id
          sign_in(@user, bypass: true)
        end

        format.html { redirect_to edit_profile_path, notice: 'Your profile has been updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:id]
        @user = User.find(params[:id])
      else
        @user = current_user
      end

      authorize @user
    end

    # Never trust parameters from the scary internet, only allow the
    # whitelist through.
    def user_params
      params.require(:user).permit(:email, :password, :application_goal,
                                   :followup_offset, :name)
                           .delete_if {|key, value| value.empty?}
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<header class="page-header">
  <h3>Misspelled your name? Fix it here.</h3>
  <h1>Edit Your Profile</h1>
</header>

<%= form_for(@user, url: profile_path, html: { method: :put }) do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <div class="alert alert-error">
        <ul>
          <li>
            <%= message %>
          </li>
        </ul>
      </div>
    <% end %>
  <% end %>

  <fieldset class="primary">
    <h3>Your details</h3>
    <div>
      <%= f.label :email %>
        <% if @user.pending_reconfirmation? %>
        <em>(<%= @user.unconfirmed_email %> is waiting for confirmation)</em>
      <% end %>
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="half-width">
      <%= f.label :"application_goal", title: 'How many jobs do you want to apply for per week?' %><em></em>
      <%= f.text_field :application_goal %>
    </div>

    <div class="half-width">
      <%= f.label :"followup_offset", title: 'This is the number of days after applying you want to send a follow-up message.' %>
      <%= f.text_field :followup_offset %>
    </div>

  </fieldset>

  <fieldset class="secondary">
    <h3>Change your password</h3>
    <div>
      <%= f.label :password %> <em>(leave blank if you don't want to change it)</em>
      <%= f.password_field :password, autocomplete: "off" %>
    </div>
  </fieldset>

  <fieldset class="important">
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Reset password token</th>
      <th>Reset password sent at</th>
      <th>Remember created at</th>
      <th>Sign in count</th>
      <th>Current sign in at</th>
      <th>Last sign in at</th>
      <th>Current sign in ip</th>
      <th>Last sign in ip</th>
      <th>Confirmation token</th>
      <th>Confirmed at</th>
      <th>Confirmation sent at</th>
      <th>Unconfirmed email</th>
      <th>Failed attempts</th>
      <th>Unlock token</th>
      <th>Locked at</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= user.confirmation_token %></td>
        <td><%= user.confirmed_at %></td>
        <td><%= user.confirmation_sent_at %></td>
        <td><%= user.unconfirmed_email %></td>
        <td><%= user.failed_attempts %></td>
        <td><%= user.unlock_token %></td>
        <td><%= user.locked_at %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @user.encrypted_password %>
</p>

<p>
  <strong>Reset password token:</strong>
  <%= @user.reset_password_token %>
</p>

<p>
  <strong>Reset password sent at:</strong>
  <%= @user.reset_password_sent_at %>
</p>

<p>
  <strong>Remember created at:</strong>
  <%= @user.remember_created_at %>
</p>

<p>
  <strong>Sign in count:</strong>
  <%= @user.sign_in_count %>
</p>

<p>
  <strong>Current sign in at:</strong>
  <%= @user.current_sign_in_at %>
</p>

<p>
  <strong>Last sign in at:</strong>
  <%= @user.last_sign_in_at %>
</p>

<p>
  <strong>Current sign in ip:</strong>
  <%= @user.current_sign_in_ip %>
</p>

<p>
  <strong>Last sign in ip:</strong>
  <%= @user.last_sign_in_ip %>
</p>

<p>
  <strong>Confirmation token:</strong>
  <%= @user.confirmation_token %>
</p>

<p>
  <strong>Confirmed at:</strong>
  <%= @user.confirmed_at %>
</p>

<p>
  <strong>Confirmation sent at:</strong>
  <%= @user.confirmation_sent_at %>
</p>

<p>
  <strong>Unconfirmed email:</strong>
  <%= @user.unconfirmed_email %>
</p>

<p>
  <strong>Failed attempts:</strong>
  <%= @user.failed_attempts %>
</p>

<p>
  <strong>Unlock token:</strong>
  <%= @user.unlock_token %>
</p>

<p>
  <strong>Locked at:</strong>
  <%= @user.locked_at %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>