config/routes.rb
Suitor::Application.routes.draw do
  devise_for :user, skip: [
    :sessions
  ], controllers: {
    confirmations: 'user/confirmations',
    invitations: 'user/invitations',
    omniauth_callbacks: 'user/omniauth_callbacks',
    registrations: 'user/registrations',
    passwords: 'user/passwords'
  }
  devise_scope :user do
    get 'use-invite' => 'user/invitations#edit', as: :invitation_accept
    get 'invite' => 'user/invitations#new', as: :new_invitation

    get 'login' => 'devise/sessions#new', as: :login
    post 'login' => 'devise/sessions#create', as: :session
    delete 'logout' => 'devise/sessions#destroy', as: :logout

    get 'sign-up' => 'user/registrations#new', as: :signup
    post 'sign-up' => 'user/registrations#create', as: :create_user_registration
  end

  resource :user, as: :profile, path: 'profile',
                  except: [:new, :show, :index, :create, :destroy]

  resources :blog, only: [:index, :show]

  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'

  # If user is logged in, show the dashboard as root
  authenticated do
    root :to => 'dashboard#index', as: :dashboard
  end

  # If user isn't logged in, show the launch page as root
  root :to => 'pages#launch'

  # Set up job postings, and routing for nested models
  resources :postings do
    get 'archived', on: :collection
    member do
      put :archivetoggle
    end
    resource :job_application do
      member do
        put 'followup'
      end
    end
    resources :interviews
    resource :offer
  end
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  VALID_FILTER_SCOPES = [:applied, :archived, :interview_completed, :interview_scheduled]

  validates :user, presence: true
  validates :title, presence: true, length: { minimum: 3 }
  validates :hiring_organization, presence: true, length: { minimum: 3 }

  belongs_to :user
  has_one :job_application, dependent: :destroy
  has_one :offer
  has_many :interviews, dependent: :destroy
  has_one :offer, dependent: :destroy
  enum role: [:user, :admin]

  # Define scopes for easier access
  default_scope -> {
    where(archived: false)
  }
  scope :offer_made, -> {
    joins(:offer).where('offers.salary IS NOT NULL')
  }
  scope :applied, -> {
    joins(:job_application).where('job_applications.date_sent IS NOT NULL')
  }
  scope :total_applied, -> {
    unscoped.joins(:job_application).where('job_applications.date_sent IS NOT NULL')
  }
  scope :applied_this_week, -> {
    joins(:job_application).where('job_applications.date_sent >= ?', Date.today.beginning_of_week)
  }
  scope :havent_applied, -> {
    where("NOT EXISTS (SELECT null FROM job_applications where job_applications.posting_id = postings.id)")
  }
  scope :needs_application, -> {
    where("NOT EXISTS (SELECT null FROM job_applications where job_applications.posting_id = postings.id) AND deadline > ?", Time.now)
  }
  scope :archived, -> {
    unscoped.where(archived: true)
  }
  scope :interview_completed, -> {
    joins(:interviews).where('interviews.datetime < ?', Time.now)
  }
  scope :interview_scheduled, -> {
    joins(:interviews).where('interviews.datetime >= ?', Time.now)
  }
  scope :with_interviews, -> {
    where("EXISTS (SELECT null FROM interviews where interviews.posting_id = postings.id)")
  }
  scope :no_interviews, -> {
    where("NOT EXISTS (SELECT null FROM interviews where interviews.posting_id = postings.id)")
  }
  scope :with_deadline, -> {
    where('deadline IS NOT NULL')
  }
  scope :deadline_approaching, -> {
    where('deadline > ?', Time.now)
  }
  scope :deadline_passed, -> {
    where('deadline < ?', Time.now)
  }
  scope :with_followup, -> {
     joins(:job_application).where('followup IS NOT NULL')
  }
  scope :without_followup, -> (followup_offset) {
     joins(:job_application).where('followup IS NULL AND job_applications.date_sent < ?', Date.current.advance(days: -followup_offset))
  }

  def self.valid_scope?(scope_name)
    if scope_name
      VALID_FILTER_SCOPES.include? scope_name.to_sym
    end
  end

  # Sort all posts by "importance", as defined by methods below
  def self.sorted_by_importance(followup_offset)
    postings = offer_made +
              interview_scheduled_or_deadline_approaching +
              unapplied_or_interview_completed +
              without_followup(followup_offset).where('deadline IS NULL').no_interviews.order('job_applications.date_sent DESC') +
              recently_applied_or_followed_up_or_deadline_passed

    # Squash duplicates.
    postings.uniq { |p| p.id }
  end

  # Find all postings with an interview scheduled, or with an application due for a deadline
  # and sort by their key dates (interview date and deadline, respectively)
  def self.interview_scheduled_or_deadline_approaching
    postings = interview_scheduled +
               havent_applied.deadline_approaching

    # We use a proxy array here because we're operating directly on
    # ActiveRecord models/objects and we can't add a property to them
    # without doing attr_accessor nonsense.
    # TODO: Make this slicker.
    key_dates = {}
    postings.each { |p|
      if p.interviews.count > 0
        key_dates[p.id] = p.interviews.upcoming.first.datetime
      else
        key_dates[p.id] = p.deadline
      end
    }

    # Squash duplicates.
    postings.uniq { |p| p.id }

    # Sort in ASC order, since these are future dates (i.e. earlier dates/deadlines come first).
    postings.sort { |p1, p2| key_dates[p1.id].to_date <=> key_dates[p2.id].to_date }
  end

  # Find all postings with an interview completed, or posts that have not been applied to,
  # and sort by their key dates (interview date and posting/updated date, respectively).
  # Ignore any posting with a deadline.
  def self.unapplied_or_interview_completed
    postings = havent_applied.where('deadline IS NULL') +
               interview_completed

    # Proxy array
    key_dates = {}
    postings.each { |p|
      if p.interviews.count > 0
        key_dates[p.id] = p.interviews.last.datetime
      elsif p.date_posted
        key_dates[p.id] = p.date_posted
      else
        key_dates[p.id] = p.updated_at
      end
    }

    # Squash duplicates.
    postings.uniq { |p| p.id }

    # Sort in DESC order, since these are past dates (i.e. later dates/deadlines come first).
    postings.sort { |p1, p2| key_dates[p2.id].to_date <=> key_dates[p1.id].to_date }
  end

  # Find all remaining postings (recently applied, followed-up, and deadline passed)
  # and sort by their key dates (applied date and follow-up, respectively).
  def self.recently_applied_or_followed_up_or_deadline_passed
    postings = deadline_passed.havent_applied.no_interviews +
               with_followup.no_interviews +
               applied.no_interviews

    # Proxy array
    key_dates = {}
    postings.each { |p|
      if p.deadline
        key_dates[p.id] = p.deadline
      elsif p.job_application.followup
        key_dates[p.id] = p.job_application.followup
      elsif p.job_application.date_sent
        key_dates[p.id] = p.job_application.date_sent
      elsif p.date_posted
        key_dates[p.id] = p.date_posted
      else
        key_dates[p.id] = p.updated_at
      end
    }

    # Squash duplicates.
    postings.uniq { |p| p.id }

    # Sort in DESC order, since these are past dates (i.e. later dates/deadlines come first).
    postings.sort { |p1, p2| key_dates[p2.id].to_date <=> key_dates[p1.id].to_date }
  end

  # Sort all posts by their application statuses
  def self.sorted_by_status
    postings = offer_made +
              interview_scheduled.order('interviews.datetime ASC') +
              havent_applied +
              no_interviews.joins(:job_application).order('job_applications.followup ASC') +
              interview_completed

    # Squash duplicates.
    postings.uniq { |p| p.id }
  end

  # These methods allow for easier checks on certain statuses of the postings
  def action_required?
    !applied? or (applied? and followup_needed?)
  end

  def applied?
    job_application and job_application.id and job_application.date_sent
  end

  def followup_needed?
    if job_application
      job_application.date_sent.advance(:days => followup_offset) < Date.current and interviews.empty? and !job_application.followup?
    end
  end

  def interview_completed?
    !interviews.empty? and interviews.upcoming.empty?
  end

  def interview_scheduled?
    !interviews.empty? and !interviews.upcoming.empty?
  end

  def offer_made?
    offer
  end

  def followup_offset
    user.followup_offset
  end

  def actionable
    return @actionable if @actionable

    @actionable ||=
      if offer_made?
        "offer-made"
      elsif interview_scheduled?
        "interview-scheduled"
      elsif interview_completed?
        "interview-completed"
      elsif followup_needed?
        "followup-needed"
      elsif !applied?
        "application-needed"
      else
        ""
      end
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  after_action :verify_authorized, except: [:index, :archived]
  after_action :verify_policy_scoped, only: [:index, :archived]
  before_action :require_login

  def index
    @sortorder = params[:sort]
    case @sortorder
      when 'date-added'
        @method = :order, 'created_at DESC'
      when 'date-posted'
        @method = :order, 'date_posted'
      when 'status'
        @method = :sorted_by_status
    else
      @sortorder = 'importance'
      @method = :sorted_by_importance, current_user.followup_offset
    end
  end

  def archived
    @method = :archived
    @archive_page = true
    render 'index'
  end

  def archivetoggle
    @posting = Posting.unscoped.find(params[:id])
    authorize @posting

    respond_to do |format|
      if @posting.toggle!(:archived)
        format.html { redirect_to @posting }
        format.json { render json: @posting }
      else
        format.html { redirect_to @posting, error: "Posting couldn't be archived." }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @posting = Posting.unscoped.find(params[:id])
    authorize @posting
    @posting.build_job_application unless @posting.job_application
    @interview = Interview.new(posting: @posting)
  end

  def new
    @posting = Posting.new
    authorize @posting
  end

  def create
    @posting = Posting.new(posting_params)
    @posting.user_id = current_user.id

    authorize @posting

    if @posting.save
      redirect_to @posting
    else
      render 'new'
    end
  end

  def edit
    @posting = Posting.unscoped.find(params[:id])
    authorize @posting
  end

  def update
    @posting = Posting.unscoped.find(params[:id])
    authorize @posting

    if @posting.update(posting_params)
      redirect_to @posting
    else
      render 'edit'
    end
  end

  def destroy
    @posting = Posting.unscoped.find(params[:id])
    authorize @posting
    if @posting.destroy
      redirect_to postings_path
    else
      redirect_to postings_path, error: "Posting couldn't be deleted."
    end
  end

  private
    def posting_params
      params.require(:posting).permit(:title, :description, :url, :date_posted, :job_location, :hiring_organization, :hiring_organization_url, :contact_name, :contact_email, :contact_number, :application_url, :deadline, :application_instructions)
    end
end

app/helpers/postings_helper.rb
module PostingsHelper
  def cache_key_for_postings(method=:all, user=current_user)
    count = policy_scope(Posting.all).count +
            policy_scope(Interview.all).count +
            policy_scope(JobApplication.all).count +
            policy_scope(Offer.all).count

    max_updated_at = []
    max_updated_at << policy_scope(Posting.all).maximum(:updated_at).try(:utc).try(:to_i)
    max_updated_at << policy_scope(Interview.all).maximum(:updated_at).try(:utc).try(:to_i)
    max_updated_at << policy_scope(JobApplication.all).maximum(:updated_at).try(:utc).try(:to_i)
    max_updated_at << policy_scope(Offer.all).maximum(:updated_at).try(:utc).try(:to_i)

    max_updated_at = max_updated_at.reject(&:blank?).max

    "postings/for-user-#{user.id}/#{method}-#{count}-#{max_updated_at}"
  end
end

app/views/postings/_form.html.erb
<%= form_for @posting, html: {class: "edit-posting"} do |f| %>
  <% if @posting.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@posting.errors.count, "error") %> prohibited this post from being saved:</h2>
      
      <ul>
        <% @posting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>  
  <% end %>

<fieldset class="job-information">

  <div>
    <%= f.label :title, "Position", class: "required" %>
    <%= f.text_field :title %>
  </div>

  <div class="half-width partial">
    <%= f.label :hiring_organization , "Company", class: "required" %>
    <%= f.text_field :hiring_organization %>
  </div>

  <div class="half-width date">
    <%= f.label :date_posted, "Date posted" %>
    <%= date_field(:posting, :date_posted) %>
    <i class="icon-calendar"></i>
  </div>

  <div class="url-field">
    <%= f.label :'url', "URL to original posting" %>
    <%= f.url_field :url %>
  </div>

  <div>
    <%= f.label :description, "Posting details" %>
    <%= f.text_area :description, class: "wysiwyg" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

</fieldset>


<fieldset class="company-information primary">

  <h3>About the company</h3>

  <div>
    <%= f.label :job_location, "Location" %>
    <%= f.text_field :job_location %>
  </div>

  <div class="url-field">
    <%= f.label :hiring_organization_url, "Company Website"  %>
    <%= f.url_field :hiring_organization_url %>
  </div>


</fieldset>

<fieldset class="application-information secondary">

  <h3>How to apply</h3>

  <div class="half-width date">
    <%= f.label :deadline, "Deadline" %>
    <%= date_field(:posting, :deadline) %>
    <i class="icon-calendar"></i>
  </div>

  <div class="half-width partial">
    <%= f.label :contact_name, "Contact Name" %>
    <%= f.text_field :contact_name %>
  </div>

  <div>
    <%= f.label :contact_number, "Phone number" %>
    <%= f.phone_field :contact_number %>
  </div>

  <div>
    <%= f.label :contact_email, "Email address" %>
    <%= f.email_field :contact_email %>
  </div>

  <div class="url-field">
    <%= f.label :application_url, "Application URL" %>
    <%= f.url_field :application_url %>
  </div>

  <div>
    <%= f.label :application_instructions, "Instructions" %>
    <%= f.text_area :application_instructions %>
  </div>

</fieldset>

<% end %>

app/views/postings/_sort_buttons.html.erb
<% buttons.each do |button| %>
  <%= link_to(postings_path :sort => button) do %>
  <% if @sortorder == button %>
    <li class="checked"><i class="icon-checkmark">
  <% else %>
    <li><i class="icon-circle-blank">
  <% end %>
    <span><%= button.titleize %></span></i></li>
  <% end %>
<% end %>

app/views/postings/edit.html.erb
<header class="page-header">
    <h1>Edit job posting</h1>
</header>

<%= render 'form' %>

app/views/postings/index.erb
<h1>All job postings</h1>

<%= link_to 'Add new job posting', new_posting_path %>
 
  <% @postings.each do |posting| %>
    <div>
      <h3><%= posting.title %></h3>
      <p><%= posting.description %></p>
    </div>
  <% end %>

app/views/postings/new.html.erb
<header class="page-header">
    <h1>Add new job posting</h1>
</header>

<%= render 'form' %>

app/views/postings/show.erb
<div>
  <h2>Title</h2>
  <%= @posting.title %>
</div>

<div>
  <h2>Description</h2>
  <%= @posting.description %>
</div>

<%= link_to 'Never-mind!', postings_path %>

app/views/postings/show.html.erb
<!-- PAGE TITLE -->
<header class="page-header">

  <h3><%= @posting.title %></h3>
  <h1><%= @posting.hiring_organization %></h1>

  <!-- CONTROL LINKS -->
  <div class="controls">
    <%= link_to edit_posting_path(@posting) do %>
      <i class="icon-pencil2"><span>Edit</span></i>
    <% end %>

    <%= link_to posting_path(@posting), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="icon-trash2"><span>Delete</span></i>
    <% end %>

    <% if @posting.url %>
      <%= link_to @posting.url do %>
          <i class="icon-link3"><span>Original posting</span></i>
      <% end %>
    <% end %>

    <%= link_to archivetoggle_posting_path(@posting), remote: true, method: :put, class: "archive-toggle", data: {id: "posting-#{@posting.id}"} do %>
      <% if @posting.archived %>
        <i class="icon-thumbs-up3"><span>Unarchive</span></i>
      <% else %>
        <i class="icon-thumbs-down3"><span>Archive</span></i>
      <% end %>
    <% end %>
  </div>
  <!-- END CONTROL LINKS -->

</header>
<!-- END PAGE TITLE -->



<!-- JOB INFORMATION -->
<section class="job-information">

  <ul class="job-details">

    <!-- Deadline or date posted -->
    <% if @posting.date_posted or @posting.deadline %>
      <li>
      <% if @posting.date_posted %>
        <i class="icon-clock4"><span>Posted</span></i> <%= short_date(@posting.date_posted) %>
      <% end %>
      <% if @posting.deadline %>
        <i class="icon-alarm2"><span>Deadline</span></i> <%= friendly_datetime(@posting.deadline) %>
      <% end %>
      </li>
    <% end %>

    <!-- Company and location -->
    <% if @posting.hiring_organization %>
      <li><i class="icon-location4"><span>Employer</span></i>
      <% if @posting.hiring_organization_url %>
        <%= link_to @posting.hiring_organization, @posting.hiring_organization_url %>
      <% else %>
        <%= @posting.hiring_organization %>
      <% end %>
      <% unless @posting.job_location.blank? %>(<%= @posting.job_location %>)<% end %>
      </li>
    <% end %>

    <!-- URL to apply online -->
    <% unless @posting.application_url.blank? %>
      <li><i class="icon-external-link"><span>Online application</span></i><%= link_to 'URL', @posting.application_url %></li>
    <% end %>

    <!-- Contact name & email -->
    <% unless @posting.contact_name.blank? or !@posting.contact_email.blank? %>
      <li><i class="icon-user6"><span>Contact</span></i>
      <% if @posting.contact_name.blank? %>
        <%= link_to @posting.contact_email, @posting.contact_email %>
      <% elsif @posting.contact_email.blank? %>
        <%= @posting.contact_name %>
      <% else %>
        <%= link_to @posting.contact_name, @posting.contact_email %>
      <% end %>
      </li>
    <% end %>

    <!-- Contact number for people who like those things -->
    <% if !@posting.contact_number.blank? %>
      <li><i class="icon-phone2"><span>Phone number</span></i>
      <%= @posting.contact_number %>
    <% end %>

  </ul>

  <!-- Job description -->
  <div class="job-description">
    <%= simple_format(@posting.description) %>
  </div>

  <!-- Application instructions -->
  <div class="application-instructions">
    <% if @posting.application_instructions %>
      <% if !@posting.application_instructions.empty? %>
      <h3><i class="icon-key2"><span></span></i>How to apply</h3>
      <%= @posting.application_instructions %>
      <% end %>
    <% end %>
  </div>

</section>
<!-- END JOB INFORMATION -->



<!-- JOB ACTIONS -->
<section class="job-actions">

  <!-- PENDING TASKS -->
  <ul class="pending-tasks">
    <% if @posting.actionable == "offer-made" %>

      <!-- Job offer -->
      <div class="job-offer">
        <h3>Congratulations! You got the job!</h3>
        <ul>
          <li>
            <i class="icon-coin"><span>Salary:</i> <%= @posting.offer.salary %></span>

            <%= link_to edit_posting_offer_path(@posting), class: 'edit-link' do %>
              <i class="icon-pencil2" title="Edit"></i>
            <% end %>

            <%= link_to posting_offer_path(@posting), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link'  do %>
              <i class="icon-trash2" title="Delete"></i>
            <% end %>
          </li>
        </ul>
        <p><%= @posting.offer.details %></p>
      </div>

    <% else %>

      <!-- Upcoming interview -->
      <% if @posting.actionable == "interview-scheduled" %>
        <li class="expander" title="Show interview details">
          <i class="icon-bubbles3"><span title="<%= full_datetime(@posting.interviews.upcoming.first.datetime) %>">Interview scheduled</i> <%= friendly_datetime(@posting.interviews.upcoming.first.datetime) %></span>

          <%= link_to edit_posting_interview_path(@posting, @posting.interviews.last), class: 'edit-link' do %>
            <i class="icon-pencil2" title="Edit"></i>
          <% end %>

          <%= link_to posting_interview_path(@posting, @posting.interviews.last), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link'  do %>
          <i class="icon-trash2" title="Delete"></i>
          <% end %>

          <i class="expand-icon icon-arrow-down9"></i>

        </li>

          <div class="expand-panel" style="display: none">
            <h3>
            <% if @posting.interviews.upcoming.first.interviewer %>
              <%= @posting.interviews.upcoming.first.interviewer %>
            <% end %>
            <% if @posting.interviews.upcoming.first.contact_method %>
              <span>via</span> <%= @posting.interviews.upcoming.first.contact_method%>
            <% end %>
            </h3>
            <div class="notes">
              <%= simple_format(@posting.interviews.upcoming.first.notes) %>
            </div>
          </div>
      <% end %>

      <!-- Follow-up required -->
      <% if @posting.followup_needed? %>
        <li><i class="followup icon-circle-blank todo" data-uri="<%= followup_posting_job_application_path(@posting) %>" data-posting-id="<%= @posting.id %>"><span>Send a follow-up</span></i></li>
      <% end %>

    <% end %>
  </ul>
  <!-- END PENDING TASKS -->



  <!-- COMPLETED TASKS -->
  <ul class="completed-tasks">

    <!-- Submitted application -->
    <% if @posting.applied? %>

      <% if @posting.job_application.cover_letter? %>
        <li class="expander" title="Show application">
      <% else %>
        <li>
      <% end %>

        <i class="icon-checkmark"><span>Application sent </span></i>
        <%= short_date(@posting.job_application.date_sent) %>

        <%= link_to edit_posting_job_application_path(@posting), class: 'edit-link' do %>
          <i class="icon-pencil2" title="Edit"></i>
        <% end %>

        <%= link_to posting_job_application_path(@posting), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link' do %>
          <i class="icon-trash2" title="Delete"></i>
        <% end %>

        <% if @posting.job_application.cover_letter? %>
          <i class="expand-icon icon-arrow-down9"></i>
        <% end %>

      </li>

      <% if @posting.job_application.cover_letter? %>
        <div class="expand-panel notes" style="display: none">
          <%= simple_format(@posting.job_application.cover_letter) %>
        </div>
      <% end %>

    <% end %>

    <!-- Completed interview -->
    <% if @posting.actionable == "interview-completed" %>

      <li class="expander" title="Show interview details">
        <i class="icon-checkmark"><span title="<%= full_datetime(@posting.interviews.last.datetime) %>">Interviewed</span></i>
        <%= friendly_datetime(@posting.interviews.last.datetime) %>

        <%= link_to edit_posting_interview_path(@posting, @posting.interviews.last), class: 'edit-link' do %>
          <i class="icon-pencil2" title="Edit"></i>
        <% end %>

        <%= link_to posting_interview_path(@posting, @posting.interviews.last), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link'  do %>
          <i class="icon-trash2" title="Delete"></i>
        <% end %>

        <i class="expand-icon icon-arrow-down9"></i>

      </li>

      <div class="expand-panel" style="display: none">
        <h3>
        <% if @posting.interviews.last.interviewer %>
          <%= @posting.interviews.last.interviewer %>
        <% end %>
        <% if @posting.interviews.last.contact_method %>
          <span>via</span> <%= @posting.interviews.last.contact_method %>
        <% end %>
        </h3>
        <div class="notes">
          <%= simple_format(@posting.interviews.last.notes) %>
        </div>
      </div>

    <% end %>

    <!-- Sent follow-up -->
    <% if @posting.job_application.followup %>
      <li>
        <i class="icon-checkmark"><span>Follow-up sent</span></i>
        <%= short_date(@posting.job_application.followup) %>
      </li>
    <% end %>

  </ul>
  <!-- END COMPLETED TASKS -->



  <!-- TO-DO TASKS -->

  <!-- Apply now form (should probably be moved to a separate view) -->
  <% if @posting.actionable != "interview-scheduled" and @posting.actionable != "interview-completed" and !@posting.applied? and @posting.actionable != "offer-made" %>

    <%= form_for([@posting, @posting.job_application], url: posting_job_application_path(@posting)) do |f| %>

      <h3>Apply now!</h3>

      <%= f.hidden_field :posting_id %>

      <%= f.label :"Date applied" %>
      <%= date_field :job_application, :date_sent, value: short_date(@posting.job_application.date_sent) %>

      <%= f.label :"Enter cover letter and/or notes." %>
      <%= f.text_area :cover_letter %>

      <div class="actions">
        <%= button_tag(:type => 'submit') do %>
          <i class="icon-checkmark"></i>Mark as applied
        <% end %>
      </div>
    <% end %>
  <% end %>

  <!-- Schedule interview form -->
  <% if @posting.actionable != "interview-scheduled" and @posting.actionable != "offer-made" %>
    <% if @posting.actionable == "interview-completed" %>
      <%= render 'interviews/form', location: "posting-detail", interview: "second" %>
    <% else %>
      <%= render 'interviews/form', location: "posting-detail", interview: "first" %>
    <% end %>
  <% end %>

  <!-- Add job offer link (should probably be its own form) -->
  <% if @posting.actionable != "offer-made" %>
    <form class="add-offer">
      <h3>Landed <span>this</span> job?</h3>
      <%= link_to new_posting_offer_path(@posting), class: 'offer' do %>
        Add offer details
      <% end %>
    </form>
  <% end %>
  <!-- END TO-DO TASKS -->

</section>
<!-- END JOB ACTIONS -->