config/routes.rb
Suitor::Application.routes.draw do
  devise_for :user, skip: [
    :sessions
  ], controllers: {
    confirmations: 'user/confirmations',
    invitations: 'user/invitations',
    omniauth_callbacks: 'user/omniauth_callbacks',
    registrations: 'user/registrations',
    passwords: 'user/passwords'
  }
  devise_scope :user do
    get 'use-invite' => 'user/invitations#edit', as: :invitation_accept
    get 'invite' => 'user/invitations#new', as: :new_invitation

    get 'login' => 'devise/sessions#new', as: :login
    post 'login' => 'devise/sessions#create', as: :session
    delete 'logout' => 'devise/sessions#destroy', as: :logout

    get 'sign-up' => 'user/registrations#new', as: :signup
    post 'sign-up' => 'user/registrations#create', as: :create_user_registration
  end

  resource :user, as: :profile, path: 'profile',
                  except: [:new, :show, :index, :create, :destroy]

  resources :blog, only: [:index, :show]

  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'

  # If user is logged in, show the dashboard as root
  authenticated do
    root :to => 'dashboard#index', as: :dashboard
  end

  # If user isn't logged in, show the launch page as root
  root :to => 'pages#launch'

  # Set up job postings, and routing for nested models
  resources :postings do
    get 'archived', on: :collection
    member do
      put :archivetoggle
    end
    resource :job_application do
      member do
        put 'followup'
      end
    end
    resources :interviews
    resource :offer
  end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :posting
  has_one :user, through: :posting
  validates :posting, presence: true, uniqueness: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  after_action :verify_authorized, except: [:index]
  after_action :verify_policy_scoped, only: [:index]
  before_action :require_login
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # def index
  #   @offers = policy_scope(Offer.all)
  # end

  def show
  end

  def new
    @offer = Offer.new
    authorize @offer
    @offer.posting = Posting.unscoped.find(params[:posting_id])
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.posting = Posting.unscoped.find(params[:posting_id])
    authorize @offer
    authorize @offer.posting, :update?

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer.posting, notice: 'Hey, way to go on the job offer! (We&rsquo;ve saved it for you.)' }
        format.json { render action: 'show', status: :created, location: @offer }
      else
        format.html { render action: 'new' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @offer.update(offer_params)
      redirect_to @offer.posting, notice: 'We&rsquo;ve updated your job offer for you.'
    else
      render 'edit'
    end
  end

  def destroy
    @offer.destroy
    redirect_to @offer.posting
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Posting.unscoped.find(params[:posting_id]).offer
      authorize @offer
    end

    def offer_params
      params.require(:offer).permit(:salary, :details, :posting_id)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for([@offer.posting, @offer], url: posting_offer_path(@offer.posting)) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :salary %>
    <%= f.text_field :salary %>
  </div>

  <div>
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/offers/edit.html.erb
<header class="page-header">
  <h3><%= @offer.posting.title %> <span>at</span> <%= @offer.posting.hiring_organization %></h3>
  <h1>Edit job offer</h1>
</header>

<%= render 'form' %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <thead>
    <tr>
      <th>Salary</th>
      <th>Details</th>
      <th>Posting</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.salary %></td>
        <td><%= offer.details %></td>
        <td><%= offer.posting %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_posting_offer_path(params[:posting_id]) %>

app/views/offers/new.html.erb
<header class="page-header">
  <h3><%= @offer.posting.title %> <span>at</span> <%= @offer.posting.hiring_organization %></h3>
  <h1>Add a job offer</h1>
</header>

<%= render 'form' %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salary:</strong>
  <%= @offer.salary %>
</p>

<p>
  <strong>Details:</strong>
  <%= @offer.details %>
</p>

<p>
  <strong>Posting:</strong>
  <%= @offer.posting %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>