config/routes.rb
Suitor::Application.routes.draw do
  devise_for :user, skip: [
    :sessions
  ], controllers: {
    confirmations: 'user/confirmations',
    invitations: 'user/invitations',
    omniauth_callbacks: 'user/omniauth_callbacks',
    registrations: 'user/registrations',
    passwords: 'user/passwords'
  }
  devise_scope :user do
    get 'use-invite' => 'user/invitations#edit', as: :invitation_accept
    get 'invite' => 'user/invitations#new', as: :new_invitation

    get 'login' => 'devise/sessions#new', as: :login
    post 'login' => 'devise/sessions#create', as: :session
    delete 'logout' => 'devise/sessions#destroy', as: :logout

    get 'sign-up' => 'user/registrations#new', as: :signup
    post 'sign-up' => 'user/registrations#create', as: :create_user_registration
  end

  resource :user, as: :profile, path: 'profile',
                  except: [:new, :show, :index, :create, :destroy]

  resources :blog, only: [:index, :show]

  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'

  # If user is logged in, show the dashboard as root
  authenticated do
    root :to => 'dashboard#index', as: :dashboard
  end

  # If user isn't logged in, show the launch page as root
  root :to => 'pages#launch'

  # Set up job postings, and routing for nested models
  resources :postings do
    get 'archived', on: :collection
    member do
      put :archivetoggle
    end
    resource :job_application do
      member do
        put 'followup'
      end
    end
    resources :interviews
    resource :offer
  end
end

app/views/layouts/_ga.erb
<% if Rails.env.production? %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= ENV["GA_ID"] %>', 'auto');
    <% if @userid %>
      ga('set', '&uid', '<%= @userid %>');
      ga('set', 'dimension1', '<%= @userid %>');
    <% end %>
    ga('send', 'pageview');

  </script>

<% end %>

app/views/layouts/_menu.html.erb
<ul class="navigation">

  <!-- LOGGED OUT USER -->
  <% unless current_user %>

    <li>
      <%= link_to (Rails.env.production? ? "#{root_path}#signup" :
                                           signup_path) do %>
        <i class="icon-signup"></i>
        <%= t('Sign up') %>
        <% if device != "mobile" %>
          <span><%= t('For a free account') %></span>
        <% end %>
      <% end %>
    </li>

    <li>
      <%= link_to about_path do %>
        <i class="icon-suitcase"></i>
        <%= t('About') %>
        <% if device != "mobile" %>
          <span><%= t('Learn more') %></span>
        <% end %>
      <% end %>
    </li>

    <li>
      <%= link_to login_path do %>
        <i class="icon-key3"></i>
        <%= t('Log in') %>
        <% if device != "mobile" %>
          <span><%= t('Track your jobs') %></span>
        <% end %>
      <% end %>
    </li>



  <!-- LOGGED IN USER -->
  <% else %>

    <li>
      <%= link_to dashboard_path do %>
        <i class="icon-dashboard2"></i>
        <%= t('Dashboard') %>
        <% if device != "mobile" %>
          <span><%= t('Your progress') %></span>
        <% end %>
      <% end %>
    </li>

  <li>
    <%= link_to new_posting_path do %>
      <i class="icon-plus3"></i>
      <%= t('Add new') %>
      <span><%= t('job posting') %></span>
    <% end %>
  </li>

  <li>
    <%= link_to postings_path do %>
      <i class="icon-list"></i>
      <%= t('List all') %>
      <span><%= t('job postings') %></span>
    <% end %>
  </li>

    <li>
      <%= link_to edit_profile_path do %>
        <i class="icon-cogs"></i>
        <%= t('Account') %>
        <% if device != "mobile" %>
          <span><%= t('Your settings') %></span>
        <% end %>
      <% end %>
    </li>

  <% end %>

</ul>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <ul>
      <li>
        <%= value.html_safe %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>suitor</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag "favicon.png?v=5", type: "image/png" %>
  <%= csrf_meta_tags %>
  <%= render partial: 'layouts/ga' %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <!-- MOBILE MENU -->
  <nav id="mobile-menu">
    <%= render "layouts/menu", device: "mobile" %>
  </nav>
  <!-- END MOBILE MENU -->

  <!-- PAGE-WRAPPER -->
  <div id="page-wrapper">
    <header class="site-header">
      <a id="mobile-menu-button" href="#mobile-menu">
        <i class="icon-menu2"><span>Menu</span></i>
      </a>

      <nav class="header-container">
        <!-- LOGO -->
        <%= link_to root_path do %>
          <%= image_tag("suitor.png", alt: "suitor", id: "logo") %>
        <% end %>

        <!-- MAIN NAVBAR -->
        <%= render "layouts/menu", device: "desktop" %>
      </nav>
    </header>

    <!-- PAGE CONTENT -->
    <div class="container">
      <%= render "layouts/messages" %>

      <% if blog_post? %>
        <%= render "blog/header" %>
      <% end %>

      <%= yield %>

      <% if blog_post? %>
        <%= render "blog/footer" %>
      <% end %>

    </div>
    <!-- END PAGE CONTENT -->

    <!-- SITE FOOTER -->
    <div class="block push"></div>
    <footer class="site-footer block">
      <div class="footer-container">
        <ul class="primary">
          <li><a href="http://twitter.com/mrsuitor"><i class="icon-twitter2"></i> Twitter</a></li>
          <li><a href="http://github.com/sarahsemark/suitor"><i class="icon-github"></i> GitHub</a></li>
          <li>
            <%= link_to blog_index_path do %>
              <i class="icon-blog"></i> Blog
            <% end %>
          </li>
          <li>
            <%= link_to about_path do %>
              <i class="icon-suitcase"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to help_path do %>
             <i class="icon-help"></i> Help!
            <% end %>
          </li>
        </ul>

        <ul class="secondary">
          <li>
            <% if current_user %>
              <%= link_to "Log out", logout_path, method: 'delete', class: 'logout' %>
            <% else %>
              <%= link_to "Log in", login_path %>
            <% end %>
            </li>
          <li><a href="javascript:void(0)">Privacy Policy</a></li>
        </ul>

        </div>
    </footer>
    <!-- END SITE FOOTER -->

  </div>
  <!-- END PAGE-WRAPPER -->

</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><%= yield :title %></title>
        <link rel="stylesheet" type="text/css" href="email.css">
        
    </head>
        <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" bgcolor="f7f7f7">
      <center>
          <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable">
              <tr>
                  <td align="center" valign="top" id="bodyCell">
                      <!-- BEGIN TEMPLATE // -->
                      <table border="0" cellpadding="0" cellspacing="0" id="templateContainer">
                          <tr>
                              <td align="center" valign="top">

                              
                                </td>
                            </tr>
                          <tr>
                              <td align="center" valign="top">
                                  <!-- BEGIN HEADER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader">
                                        <tr>
                                            <td valign="top" class="headerContent">
                                              <a href="http://mrsuitor.com"><%= image_tag "suitor_600.png", id: "headerImage", alt: "suitor" %></a>
                                              <h1><%= yield :title %></h1>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END HEADER -->
                                </td>
                            </tr>

    <tr>
      <td align="center" valign="top">
          <!-- BEGIN BODY // -->
            <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateBody">
                <tr>
                    <td valign="top" class="bodyContent" mc:edit="body_content">

  <%= yield %>

<p class="xo"><a href="http://mrsuitor.com">&hearts; suitor xox</a></p>
                    </td>
                </tr>
            </table>
            <!-- // END BODY -->
        </td>
    </tr>
                                </table>
                        <!-- // END TEMPLATE -->
                    </td>
                </tr>
            </table>
        </center>
    </body>
</html>

app/views/layouts/skeleton.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>suitor</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.png?v=5', type: 'image/png' %>
  <%= csrf_meta_tags %>
  <%= render partial: 'layouts/ga' %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <%= yield %>

</body>
</html>